SELECT M.PATIENT
	 , M.ENCOUNTER
	 , M.DESCRIPTION AS MEDICATION
     , STRING_AGG (DISTINCT E.REASONDESCRIPTION,',') AS REASON
FROM MEDICATIONS M
JOIN ENCOUNTERS E
ON M.PATIENT = E.PATIENT
WHERE M.DESCRIPTION ILIKE 'Cef%'
AND E.REASONDESCRIPTION IS NOT NULL
GROUP BY 1,2,3
;